### PR TITLE
Escape abbreviation before substitution

### PR DESCRIPTION
**Pull request by matthen**
Fixes https://github.com/nipunsadvilkar/pySBD/issues/80

### CODE REVIEW

**Comment by matthen** [comment]
Perhaps there should be some unit tests for these functions?

**Comment by nipunsadvilkar** [comment]
Hey @matthen, Sorry for the late reply! was tied up in other commitments.

Yes, adding those unit tests would definitely help. Since PySBD is inspired by https://github.com/diasks2/pragmatic_segmenter, have kept tests and design pretty similar. Having said that, more tests are always welcome :)

Also, can you please take a pull from master? I've fixed the failing CI issue

**Comment by matthen** [comment]
Thanks Nipun! I have updated the branch and it looks like CI is passing. How about a separate PR to add a unit test that checks https://github.com/nipunsadvilkar/pySBD/issues/80 ?

**Comment by nipunsadvilkar** [comment]
Yes separate PR would be fine

**Pull request merged**
