### PR TITLE
Slovak lang support

### PR DESCRIPTION
**Pull request by misotrnka**
We've added support for SBD in Slovak language text.

Language specific improvements:

- list of common slovak abbreviations
- list of prepositive abbreviations
- list of number abbreviations
- handling of roman numerals
- handling of `„ text “` quotes, that are common in Slovak language
- handling of ordinal numerals in dates, such as `17. Apríl 2020`
- modified the replacement of periods in abbreviations, so it can consistently handle common Slovak abbreviations such as `Company Name s. r. o.`
- disabled processing of alphabetical lists, because of conflicts with some common abbreviations

The code has been tested for stability on a very large corpus of web text. The has been no rigorous testing for segmentation quality, but the subjective feeling in the team is very positive.

### CODE REVIEW

**Comment by nipunsadvilkar** [comment]
@misotrnka That's great! ✨ 

Can you add some tests for Slovak language as well?

Refer:
https://github.com/nipunsadvilkar/pySBD/blob/master/tests/lang/test_polish.py
https://github.com/nipunsadvilkar/pySBD/blob/master/tests/lang/test_russian.py

These tests will also act as a Golden Rules Set for Slovak language.

**Comment by misotrnka** [comment]
@nipunsadvilkar Will try to add the tests soon. :+1:

**Comment by misotrnka** [comment]
@nipunsadvilkar Ok, please check now, I've added a few tests.

**Comment by nipunsadvilkar** [comment]
Great 💯 

@misotrnka Can you please take a pull from master? I've fixed the failing CI issue

**Comment by misotrnka** [comment]
Ok, looks good now :sunglasses:

**Comment by nipunsadvilkar** [comment]
@misotrnka Thanks for adding support for Slovak 👍

**Pull request merged**
